import { Rubik } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "../context/AuthContext";

const rubik = Rubik({
  variable: "--font-rubik",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html>
      <body className={`${rubik.variable}`}>
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
